# ifndef CONFIG_H  
# define CONFIG_H  
# define APPNAME "Q Light Controller Plus"  
# define FXEDNAME "Fixture Definition Editor"  
# define APPVERSION "4.12.2 GIT"  
# define DOCSDIR "Documents"  
# define INPUTPROFILEDIR "InputProfiles"  
# define USERQLCPLUSDIR "QLC+"  
# define USERINPUTPROFILEDIR "QLC+/InputProfiles"  
# define MIDITEMPLATEDIR "MidiTemplates"  
# define USERMIDITEMPLATEDIR "QLC+/MidiTemplates"  
# define MODIFIERSTEMPLATEDIR "ModifiersTemplates"  
# define USERMODIFIERSTEMPLATEDIR "QLC+/ModifiersTemplates"  
# define FIXTUREDIR "Fixtures"  
# define USERFIXTUREDIR "QLC+/Fixtures"  
# define PLUGINDIR "Plugins"  
# define AUDIOPLUGINDIR "Plugins/Audio"  
# define TRANSLATIONDIR ""  
# define RGBSCRIPTDIR "RGBScripts"  
# define USERRGBSCRIPTDIR "QLC+/RGBScripts"  
# define GOBODIR "Gobos"  
# define WEBFILESDIR "Web"  
#define MESHESDIR "Meshes"
#define COLORFILTERSDIR "ColorFilters"
#define USERCOLORFILTERSDIR "QLC+/ColorFilters"
#define KExtColorFilters ".qxcf"
# endif 
